import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {metric,windowFromStart,fingerprint} from '../scripts/growth-scorecard/core.mjs';
import {classifyLateData,applyCorrection,resumeCorrections,canonicalRow,recentFinalWeeks,persistReview} from '../scripts/growth-scorecard/late-data.mjs';
import {notionProperties} from '../scripts/growth-scorecard/notion.mjs';
import {weekManifest,saveLifecycle,readLifecycle,finalWeekMatches} from '../scripts/growth-scorecard/week-lifecycle.mjs';
import {ensureWeeklyHistory,canonicalBlock,readTree,warehouseRows} from '../scripts/growth-scorecard/meeting.mjs';
import {trendDelta} from '../scripts/growth-scorecard/reporting-semantics.mjs';
import {reportingCredentials,AS_REPORTING} from '../scripts/growth-scorecard/apple-reporting-auth.mjs';
import {collectApple} from '../scripts/growth-scorecard/stores.mjs';
const app={key:'easyspell',name:'EasySpell',iosAppleId:'6762075035'},week=windowFromStart('2026-09-07');
const row=n=>metric(week,app,'Store Downloads','Android',{value:n*9,status:'EARLY',source:'Google Play GCS stats/installs',sourceAccount:'current',definition:'google_daily_device_installs_v1',sourceTimezone:'UTC',unit:'devices',population:null,complete:n===7,coverage:{dates:Array.from({length:n},(_,i)=>`2026-09-${String(7+i).padStart(2,'0')}`),observedDays:n,expectedDays:7},sourceEvidence:{v:1,kind:'sum',dates:Object.fromEntries(Array.from({length:n},(_,i)=>[`2026-09-${String(7+i).padStart(2,'0')}`,{value:9}])),references:['export.csv']},notes:n===7?'Complete source dates':'PARTIAL '+n+'/7'});
test('FINAL 4/7 to 7/7 and intermediate 6/7 are allowed only with unchanged observed daily values',()=>{assert.equal(classifyLateData(row(4),row(7)).state,'SAFE_LATE_DATA');assert.equal(classifyLateData(row(4),row(6)).state,'SAFE_LATE_DATA');});
test('changed observed date is a provider revision with exact changed dates',()=>{const n=row(7);n.sourceEvidence.dates['2026-09-07'].value++;n.value++;const r=classifyLateData(row(4),n);assert.equal(r.state,'PROVIDER_REVISION_REVIEW');assert.deepEqual(r.changedObservedDates,['2026-09-07']);});
test('source, definition, country, calendar, population and currency changes require review',()=>{for(const [key,value]of Object.entries({source:'UI',definition:'new',country:'TR',sourceTimezone:'Pacific',population:'other',currency:'USD'})){const r=classifyLateData(row(4),{...row(7),[key]:value});assert.equal(r.state,'PROVIDER_REVISION_REVIEW',key);}});
test('equivalent source approval is row-specific and cannot override definition or observed revisions',()=>{const old=row(4),candidate={...row(7),source:'approved-source'},equivalentSources=[{approvalId:'manual-1',rowKey:old.id,from:old.source,to:candidate.source}];assert.equal(classifyLateData(old,candidate,{equivalentSources}).state,'SAFE_LATE_DATA');candidate.definition='changed';assert.equal(classifyLateData(old,candidate,{equivalentSources}).state,'PROVIDER_REVISION_REVIEW');});
test('missing daily evidence or inconsistent totals cannot auto correct; unavailable is not zero',()=>{const old=row(4);delete old.sourceEvidence;assert.equal(classifyLateData(old,row(7)).state,'PROVIDER_REVISION_REVIEW');assert.equal(classifyLateData(row(4),{...row(7),value:null,status:'WAITING'}).state,'NO_NEW_DATA');assert.equal(classifyLateData(row(4),{...row(7),value:0}).state,'PROVIDER_REVISION_REVIEW');});
test('only four newest FINAL weeks selected, OPEN ignored',()=>{const weeks=Object.fromEntries(['2026-07-27','2026-08-03','2026-08-10','2026-08-17','2026-08-24'].map(w=>[w,{status:'FINAL'}]));weeks['2026-08-31']={status:'OPEN'};assert.deepEqual(recentFinalWeeks({weeks}),['2026-08-24','2026-08-17','2026-08-10','2026-08-03']);});
async function fixture(){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'late-data-')),config={apps:[app],archiveBackupDirectory:dir,lifecycleFile:path.join(dir,'lifecycle.json'),lateData:{directory:dir},notion:{databaseId:'db',parentPageId:'parent'}};
 const old=row(4),pages=[{id:'row1',properties:notionProperties(old,'2026-09-14')},{id:'open',properties:notionProperties({...row(4),week:'2026-09-14',id:'open'},'2026-09-14')}];
 const entries=new Map(),children=new Map([['parent',[]]]);let counter=0,patches=0,fail=false;
 const add=(parent,b)=>{const id='b'+(++counter),entry={...structuredClone(b),id,has_children:!!b[b.type]?.children?.length};entries.set(id,entry);children.set(id,[]);children.get(parent).push(entry);for(const c of b[b.type]?.children||[])add(id,c);if(entry[b.type])delete entry[b.type].children;return entry;};
 const api=async(endpoint,method='GET',body)=>{
  if(endpoint==='pages'&&method==='POST'){const id='p'+(++counter),title=body.properties.title.title[0].text.content;entries.set(id,{id,is_locked:false});children.set(id,[]);children.get(body.parent.page_id).push({id,type:'child_page',child_page:{title},has_children:false});for(const b of body.children||[])add(id,b);return entries.get(id);}
  const match=endpoint.match(/^blocks\/([^/]+)\/children/);if(match){if(method==='PATCH')return {results:body.children.map(b=>add(match[1],b)),has_more:false};return {results:structuredClone(children.get(match[1])||[]),has_more:false};}
  if(endpoint.startsWith('blocks/')&&method==='DELETE'){const id=endpoint.split('/')[1];for(const [p,list]of children)children.set(p,list.filter(b=>b.id!==id));return {};}
  if(endpoint.startsWith('pages/')){const id=endpoint.split('/')[1],p=pages.find(p=>p.id===id)||entries.get(id);if(method==='PATCH'){if(body.properties){Object.assign(p.properties,body.properties);patches++;if(fail){fail=false;throw Error('simulated response loss');}}else Object.assign(p,body);}return structuredClone(p);}
  throw Error('Unexpected '+method+' '+endpoint);
 };
 saveLifecycle(config,{weeks:{[week.start]:{status:'FINAL',...weekManifest(pages,week.start),snapshot:{status:'BUILDING',capturedAt:'2026-09-18T22:00:00Z'}},'2026-09-14':{status:'OPEN'}}});
 const render=()=>({blocks:[{object:'block',type:'paragraph',paragraph:{rich_text:[{type:'text',text:{content:'Canonical projection'}}]}}]});
 await ensureWeeklyHistory(config,pages,api,render);
 const refresh=async p=>{await ensureWeeklyHistory(config,p,api,render);assert.equal(warehouseRows(p,week.start,readLifecycle(config))[0].finalizedVerified,true);};
 return {config,pages,api,list:async()=>structuredClone(pages),refresh,old:canonicalRow(pages[0],config),patches:()=>patches,setFail:()=>{fail=true;},dir};
}
test('safe correction verifies canonical, rebuilds/relocks snapshot, refreshes canonical view, leaves OPEN untouched and replay is idempotent',async()=>{const f=await fixture();try{const open=structuredClone(f.pages[1]),changes=[{old:f.old,candidate:row(7)}],deps={api:f.api,list:f.list,refresh:f.refresh};const r=await applyCorrection(f.config,{week:week.start,changes,runId:'run1'},deps);assert.equal(r.state,'COMMITTED');assert.equal(f.pages[0].properties.Value.number,63);assert.deepEqual(f.pages[1],open);const entry=readLifecycle(f.config).weeks[week.start];assert.equal(entry.snapshot.status,'VERIFIED');assert.equal((await f.api('pages/'+entry.snapshot.pageId)).is_locked,true);assert.match(JSON.stringify(await readTree(f.api,entry.snapshot.pageId)),/Corrected after late provider data/);assert.ok(finalWeekMatches(f.pages,week.start,entry));const corrected=warehouseRows(f.pages,week.start,readLifecycle(f.config))[0],next={...corrected,week:'2026-09-14',value:72,semantics:{...corrected.semantics,coverage:{...corrected.semantics.coverage,dates:corrected.semantics.coverage.dates.map(d=>new Date(Date.parse(d+'T12:00:00Z')+7*86400000).toISOString().slice(0,10))}}};assert.equal(trendDelta(next,corrected),'↑14.3%');const repeat=await applyCorrection(f.config,{week:week.start,changes,runId:'run2'},deps);assert.equal(repeat.replay,true);assert.equal(f.patches(),1);assert.equal(fs.readdirSync(f.dir).filter(f=>f.startsWith('correction-')&&f.endsWith('.local.json')).length,1);}finally{fs.rmSync(f.dir,{recursive:true,force:true});}});
test('uncertain write response resumes the prepared journal without duplicate row mutation',async()=>{const f=await fixture();try{const deps={api:f.api,list:f.list,refresh:f.refresh};f.setFail();await assert.rejects(applyCorrection(f.config,{week:week.start,changes:[{old:f.old,candidate:row(7)}],runId:'run1'},deps),/response loss/);await resumeCorrections(f.config,deps);assert.equal(f.patches(),1);assert.equal(readLifecycle(f.config).weeks[week.start].snapshot.status,'VERIFIED');}finally{fs.rmSync(f.dir,{recursive:true,force:true});}});
test('review evidence is idempotent and never touches canonical',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'review-'));try{const cfg={lateData:{directory:dir}},r=classifyLateData(row(4),{...row(7),source:'UI'});assert.equal(persistReview(cfg,r,'one'),persistReview(cfg,r,'two'));assert.equal(fs.readdirSync(dir).length,1);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('reporting credentials resolve separately and never fall back to App Manager secret',()=>{const names=[];const r=reportingCredentials({keychainPrefix:'kantlabs',reportingAuth:AS_REPORTING},{env:{},readSecret:name=>(names.push(name),name.endsWith('key-id')?'NEWKEY1234':'BASE64')});assert.equal(r.ascKeyId,'NEWKEY1234');assert.ok(!names.includes('kantlabs-asc-api-key-p8-b64'));assert.equal(reportingCredentials({reportingAuth:AS_REPORTING},{env:{},readSecret:()=>null}),null);assert.throws(()=>reportingCredentials({reportingAuth:AS_REPORTING},{env:{ASC_REPORTING_ISSUER_ID:'wrong'},readSecret:()=>null}),/issuer mismatch/);});
test('Apple API 403 retains dated authenticated UI fallback and daily evidence',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'apple-fallback-')),cwd=process.cwd(),original=global.fetch;try{process.chdir(dir);fs.mkdirSync('docs/weekly-app-growth',{recursive:true});fs.writeFileSync('docs/weekly-app-growth/apple-console-easyspell.local.json',JSON.stringify({app:app.key,appleId:app.iosAppleId,week:week.start,metric:'Product Page Views',sourceTimezone:'UTC',rows:['Sep 7, 2026 10','Sep 8, 2026 20']}));global.fetch=async()=>new Response('{}',{status:403});const rows=await collectApple({apps:[app]},week,[{label:'AS',token:'dummy',apps:[{id:app.iosAppleId}],vendorNumbers:[]}],{metrics:['Product Page Views']});assert.equal(rows.length,1);assert.equal(rows[0].value,30);assert.equal(rows[0].complete,false);assert.equal(rows[0].coverage.observedDays,2);assert.equal(rows[0].sourceEvidence.dates['2026-09-08'].value,20);}finally{global.fetch=original;process.chdir(cwd);fs.rmSync(dir,{recursive:true,force:true});}});
test('missing GCS export preserves actual PARTIAL UI count and never becomes zero',async()=>{const {collectPlay}=await import('../scripts/growth-scorecard/stores.mjs');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'play-fallback-')),cwd=process.cwd(),playApp={...app,androidPackage:'co.kantlabs.easyspell',playOwnershipVerified:true};try{process.chdir(dir);fs.mkdirSync('docs/weekly-app-growth',{recursive:true});fs.writeFileSync('docs/weekly-app-growth/play-console-easyspell.local.json',JSON.stringify({app:app.key,package:playApp.androidPackage,week:week.start,observedAt:'2026-09-15T00:00:00Z',rows:[10,11,12,13].map(d=>`${d} Eyl 2026 Toplamdaki yüzdesi 9 %100`)}));const rows=await collectPlay({apps:[playApp],playAccounts:[{label:'current'}]},week,{metrics:['Store Downloads'],readExport:async()=>{throw Object.assign(Error('missing'),{status:404});}});assert.equal(rows.length,1);assert.equal(rows[0].value,36);assert.equal(rows[0].coverage.observedDays,4);assert.equal(rows[0].complete,false);assert.match(rows[0].notes,/HTTP 404/);}finally{process.chdir(cwd);fs.rmSync(dir,{recursive:true,force:true});}});
