import {metric} from './core.mjs';
export async function collectFirstParty(config,week){return config.apps.filter(a=>a.firstParty).flatMap(a=>['iOS','Android'].map(p=>metric(week,a,'Purchaser Paywall Source Distribution',p,{pillar:'Monetization',unit:'distribution',source:'First-party canonical paywall / RevenueCat linkage',sourceAccount:a.firstParty[p.toLowerCase()],status:'WAITING',notes:'No verified deterministic join from paywall_view_id / user identity to initial RevenueCat transaction. Modelled or temporal joins forbidden. Linkage remains roadmap; no instrumentation added.'})));}

// Read only identity-free pre-aggregated counters. Reuse the app's existing
// secure environment; never export credentials, identities, or customer tables.
export async function collectIOSAggregate(config,week){
 const app=config.apps.find(a=>a.key==='easyspell'),cfg=app?.firstPartyAggregate;if(!cfg)return [];
 const fs=await import('node:fs'),cp=await import('node:child_process');
 const {promisify}=await import('node:util'),run=promisify(cp.execFile);
 const env=fs.readFileSync(cfg.envFile,'utf8'),raw=env.match(/^DATABASE_URL\s*=\s*(.+)$/m)?.[1]?.trim().replace(/^['"]|['"]$/g,'');
 const u=new URL(raw);if(u.hostname!==cfg.expectedHost)throw Error('Aggregate database identity changed');
 if(!/^\d{4}-\d{2}-\d{2}$/.test(week.start)||!/^\d{4}-\d{2}-\d{2}$/.test(week.end))throw Error('Invalid week');
 const sql=`SELECT coalesce(json_agg(x),'[]') FROM (SELECT event_name,dimension_key,dimension_value,sum(count)::int AS count,array_agg(DISTINCT day ORDER BY day) AS dates,array_agg(DISTINCT app_version ORDER BY app_version) AS versions FROM product_event_counts WHERE day BETWEEN '${week.start}' AND '${week.end}' AND platform='ios' AND app_version ~ '^[0-9]+[.][0-9]+[.][0-9]+$' AND event_name IN ('app_opened','session_started','learning_session_started','learning_session_completed','activity_completed','story_session_completed','onboarding_completed','paywall_viewed','purchase_started','purchase_completed','subscription_activated') AND dimension_key IN ('all','distribution_channel') GROUP BY event_name,dimension_key,dimension_value ORDER BY event_name,dimension_key,dimension_value) x`;
 const {stdout}=await run(cfg.psqlPath||'psql',['-X','-q','-A','-t','-c',sql],{env:{...process.env,PGHOST:u.hostname.replace('-pooler.','.'),PGPORT:u.port||'5432',PGDATABASE:u.pathname.slice(1),PGUSER:decodeURIComponent(u.username),PGPASSWORD:decodeURIComponent(u.password),PGSSLMODE:'require',PGOPTIONS:'-c default_transaction_read_only=on -c statement_timeout=15000'},timeout:25000,maxBuffer:1024*1024});
 const values=JSON.parse(stdout.trim());return values.filter(r=>r.dimension_key==='distribution_channel'&&r.dimension_value==='app_store').map(r=>{
  const total=values.find(x=>x.event_name===r.event_name&&x.dimension_key==='all')?.count,test=values.find(x=>x.event_name===r.event_name&&x.dimension_value==='testflight')?.count||0,dates=r.dates.map(x=>String(x).slice(0,10));
  return metric(week,app,['onboarding_completed','paywall_viewed','purchase_started','purchase_completed','subscription_activated'].includes(r.event_name)?'iOS Aggregate Monetization Activity':'iOS Aggregate Usage','iOS',{pillar:['onboarding_completed','paywall_viewed','purchase_started','purchase_completed','subscription_activated'].includes(r.event_name)?'Monetization':'Retention & Engagement',segment:r.event_name,value:r.count,status:'EARLY',unit:'event occurrences',source:'First-party identity-free production aggregate counters',sourceAccount:cfg.projectId+'/'+cfg.branchId,sourceTimezone:'UTC ingestion day',definition:'identity_free_app_store_event_occurrences_v1',complete:false,population:JSON.stringify({platform:'ios',distributionChannel:'app_store',versionFilter:'numeric-release',versions:r.versions}),coverage:{dates,observedDays:dates.length,expectedDays:7,queryStart:week.start,queryEnd:week.end,queriedDays:7},notes:'Production branch and endpoint verified with Neon metadata. Existing distribution_channel=app_store only; numeric release versions; excludes TestFlight '+test+' and unlabelled-channel '+(total-r.count-test)+' occurrences. '+r.event_name+' occurrences, NOT unique users or deduplicated sessions; ingestion-day buckets. Observed app-store channel dates '+dates.join(', ')+'. Partial version/channel coverage. All seven UTC dates queried; observed dates mean dates with matching records, not query coverage or telemetry uptime. Compatible aggregate completion/start event ratio only; no same-session conversion, user reach, retention or country inference.'});
 });
}
