import {productEvents} from './product-export.mjs';
import {eligibleEvent,populationFor} from './release-validation.mjs';
import {rawOzardMetrics} from './mixpanel-raw.mjs';
import {metric,keychain,addDays} from './core.mjs';
const lifecycle=new Set(['app_opened','app_backgrounded','app_became_active','session_started','session_ended','app_first_opened']);
const passive=new Set(['proactive_paywall_suppressed','subscription_sync_started','subscription_sync_completed','subscription_sync_failed','subscription_state_resolved','daily_quota_prefetched','daily_quota_prefetch_failed','free_limit_state_checked','rating_value_moment_recorded','rating_prompt_evaluated','rating_negative_signal_recorded','rating_prompt_native_requested','rating_prompt_native_completed']);
const knownOther=new Set(['auth_screen_viewed','auth_method_selected','auth_started','auth_succeeded','auth_failed','auth_signed_out','user_signed_in','user_signed_out','subject_created','subject_opened','subject_deleted','note_ask_ozard_opened','youtube_link_opened','chat_tool_requested','chat_session_started','chat_session_opened','chat_message_sent','chat_response_failed','quiz_started','quiz_completed','quiz_restarted','note_creation_started','upload_started','upload_completed','upload_failed','note_generation_started','note_generation_completed','note_generation_failed','note_created_pending','note_failed','note_completed','note_created','notes_created','note_saved','note_deleted','note_title_edited','note_pdf_export_started','note_pdf_exported','note_pdf_export_failed','solver_subject_selected','solver_mode_selected','solver_started','solver_failed','solver_history_item_opened','problem_image_upload_cancelled','flashcards_generation_started','flashcards_generation_completed','flashcards_generation_failed','flashcards_started','flashcards_viewed','flashcard_viewed','flashcard_graded','flashcards_completed','podcast_mode_selected','podcast_voice_selected','podcast_onboarding_started','podcast_onboarding_completed','podcast_generation_started','podcast_created','podcast_generation_completed','podcast_generated','podcast_played','podcast_completed','short_video_concepts_started','short_video_concepts_completed','short_video_generation_started','study_mission_draft_started','study_mission_action_failed','settings_target_exam_changed','rating_store_link_opened','chat_podcast_note_selected','note_opened','quiz_generation_started','quiz_generation_completed','quiz_generation_failed']);
export const isCore=e=>e.event==='note_opened'?(e.properties.note_status==='completed'||e.properties.source==='library'&&e.properties.has_lecture_notes===true):['quiz_question_answered','chat_response_received','solver_completed','podcast_started'].includes(e.event);
export function diagnosticBucket(events){
 const kinds=new Set();for(const e of events){const n=e.event,p=e.properties;if(lifecycle.has(n)||passive.has(n))continue;
  if(n.startsWith('onboarding_')||n.startsWith('auth_')||['user_signed_in','user_signed_out'].includes(n))kinds.add('onboarding');
  else if(n.startsWith('paywall_')||n.startsWith('purchase_')||n.endsWith('_blocked_by_paywall')||['free_limit_reached','daily_quota_blocked','chat_message_limit_reached'].includes(n))kinds.add('gate');
  else if(['screen_viewed','button_clicked'].includes(n)){
   // Generic clicks have no guaranteed semantic action; retain them as observed
   // navigation/clicks rather than calling them product completion.
   if(/onboarding|welcome|login/i.test(p.screen_name||''))kinds.add('onboarding');else if(/paywall/i.test(p.screen_name||''))kinds.add('gate');else kinds.add('browse');
  }else if(['chat_viewed','notes_home_viewed','quiz_viewed'].includes(n))kinds.add('browse');
  else if(knownOther.has(n))kinds.add('other');else kinds.add('unknown');
 }
 if(kinds.has('unknown'))return 'Unclassified tracked actions';
 if(kinds.has('other'))return 'Other known non-core flows';
 if(kinds.has('onboarding')&&kinds.has('gate'))return 'Onboarding / sign-in + paywall / gate';
 if(kinds.has('onboarding'))return kinds.has('browse')?'Onboarding / sign-in + navigation':'Onboarding / sign-in only';
 if(kinds.has('gate'))return kinds.has('browse')?'Paywall / gate + navigation':'Paywall / gate only';
 if(kinds.has('browse'))return 'Browse / navigation / clicks only';
 return 'Opened; no meaningful tracked action';
}
export function usageRows(events,app,week){
 const seen=new Set(),clean=events.filter(e=>{const p=e.properties,k=JSON.stringify([e.event,p.distinct_id,p.time,p.$insert_id||null]);if(seen.has(k))return false;seen.add(k);return p.distinct_id&&['ios','android'].includes(p.platform)&&(app.key!=='easyspell'||p.platform==='android')&&eligibleEvent(app,p)&&p.time>=Math.max(Date.parse(week.startAt),app.mixpanel.cleanSince?Date.parse(app.mixpanel.cleanSince):0)&&p.time<Date.parse(week.endAt);});
 const rows=app.key==='ozard'?rawOzardMetrics(clean,app,week).filter(r=>['Weekly Active Users','Core Value Reach','Feature Value Reach'].includes(r.metric)):[];for(const platform of (app.key==='easyspell'?['Android']:['iOS','Android'])){
  const ev=clean.filter(e=>e.properties.platform===platform.toLowerCase()),byUser=new Map();for(const e of ev){const id=e.properties.distinct_id;if(!byUser.has(id))byUser.set(id,[]);byUser.get(id).push(e);}
  const active=new Set(ev.filter(e=>e.event==='session_started').map(e=>e.properties.distinct_id));
  const core=app.key==='easyspell'?e=>e.event==='activity_completed'&&e.properties.activity_schema_version==='activity_v1':isCore;
  const coreIds=new Set(ev.filter(e=>core(e)&&active.has(e.properties.distinct_id)).map(e=>e.properties.distinct_id));const noCore=[...active].filter(id=>!coreIds.has(id));
  const base={pillar:'Retention & Engagement',source:'Mixpanel raw export / existing events; in-memory active identity intersection',sourceAccount:app.mixpanel.projectId,sourceTimezone:week.timezone,definition:'usage_coverage_active_intersection_v1',population:populationFor(app,platform),status:'EARLY',complete:true,unit:'unique identity clusters',denominator:active.size,notes:'Validated build population; WAU=session_started identities. Core union intersects WAU. No cross-platform deduplication or unique-person claim. Event identities stay in memory; only aggregate counts persisted. Tester coverage remains EARLY.'};
  const emit=(name,value,extra={})=>rows.push(metric(week,app,name,platform,{...base,value,...extra}));
  emit('Any Core Value Users',coreIds.size);emit('No Core Value Users',noCore.length);emit('No Core Value Reach',active.size?noCore.length/active.size:null,{unit:'ratio',numerator:noCore.length});
  if(app.key==='easyspell'){emit('Weekly Active Users',active.size);emit('Core Value Reach',active.size?coreIds.size/active.size:null,{unit:'ratio',numerator:coreIds.size});const types=new Set(ev.filter(core).map(e=>e.properties.activity_type).filter(Boolean));for(const type of types){const matching=ev.filter(e=>core(e)&&e.properties.activity_type===type);emit('Observed Activity Completions',matching.length,{segment:type,unit:'event occurrences'});}}
  else{const groups=new Map();for(const id of noCore){const userEvents=byUser.get(id),bucket=diagnosticBucket(userEvents);if(!groups.has(bucket))groups.set(bucket,[]);groups.get(bucket).push(userEvents);}
   for(const [bucket,users]of groups){const actions={};for(const es of users)for(const n of new Set(es.map(e=>e.event).filter(n=>!lifecycle.has(n)&&!passive.has(n))))actions[n]=(actions[n]||0)+1;const top=Object.entries(actions).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([n,c])=>n+': '+c).join('; ');emit('No Core Value Diagnostic Users',users.length,{segment:bucket,denominator:noCore.length,notes:base.notes+' Disjoint precedence: unknown → known other non-core → onboarding+gate → onboarding → gate → browse/click → lifecycle. Generic clicks are not proof of completed value. Counts sum to No Core Value Users. Within-bucket observed event-user counts (overlapping, not summed): '+top+'.'});}
  }
  if(app.key==='ozard'){
   const groups=new Map();for(const id of active){const sessions=byUser.get(id).filter(e=>e.event==='session_started');const codes=new Set(sessions.map(e=>e.properties.mp_country_code));const country=codes.size===1&&/^[A-Z]{2}$/.test([...codes][0]||'')?[...codes][0]:'UNKNOWN';if(!groups.has(country))groups.set(country,[]);groups.get(country).push(id);}
   for(const[country,users]of groups){const n=users.filter(id=>coreIds.has(id)).length;const geo={country,geoDefinition:'Stable Mixpanel mp_country_code across weekly session starts; missing/changing country=UNKNOWN',notes:base.notes+' Stable IP-derived session country; learner_country is not substituted. Country unique clusters partition WAU. Small country ratios suppressed unless denominator >=100, core >=10 and non-core >=10.'};emit('Weekly Active Users',users.length,{...geo,denominator:users.length});emit('Any Core Value Users',n,{...geo,denominator:users.length});if(country!=='UNKNOWN'&&users.length>=100&&n>=10&&users.length-n>=10)emit('Core Value Reach',n/users.length,{...geo,unit:'ratio',numerator:n,denominator:users.length});}
  }
  const coreEvents=ev.filter(e=>core(e)&&coreIds.has(e.properties.distinct_id));const missing=coreEvents.some(e=>!e.properties.session_id);const repeat=[...coreIds].filter(id=>new Set(coreEvents.filter(e=>e.properties.distinct_id===id).map(e=>e.properties.session_id)).size>=2).length;
  emit('Repeat Core Value Users',missing?null:repeat,{status:missing?'WAITING':'EARLY',notes:base.notes+' At least two distinct session_id values containing a canonical core-value event. '+(missing?'Some core events lack session_id; repeat-session metric withheld.':'Complete session IDs on core events.')});
 }
 return rows;
}
export async function exportUsage(app,week){
 if(app.mixpanel.releaseValidation)return usageRows(await productEvents(app,week),app,week);
 const prefix=app.key.toUpperCase(),legacy=keychain('viberboyz-mixpanel-'+app.key+'-api-secret');const user=process.env['MIXPANEL_'+prefix+'_SERVICE_ACCOUNT_USERNAME']||process.env.MIXPANEL_SERVICE_ACCOUNT_USERNAME,secret=process.env['MIXPANEL_'+prefix+'_SERVICE_ACCOUNT_SECRET']||process.env.MIXPANEL_SERVICE_ACCOUNT_SECRET;
 if(!legacy&&(!user||!secret))throw Error('Existing export credential unavailable');
 const versions=app.mixpanel.versions||[app.mixpanel.minVersion];const where='('+versions.map(v=>'properties["app_version"] == "'+v+'"').join(' or ')+')'+(app.key==='easyspell'?' and properties["platform"] == "android"':'');
 const q=new URLSearchParams({from_date:addDays(week.start,-1),to_date:week.end,time_in_ms:'true',where,...(!legacy?{project_id:app.mixpanel.projectId}:{})});
 const r=await fetch('https://data.mixpanel.com/api/2.0/export?'+q,{headers:{Authorization:'Basic '+Buffer.from(legacy?legacy+':':user+':'+secret).toString('base64')},signal:AbortSignal.timeout(240000)});if(!r.ok){await r.body?.cancel();if(app.key==='easyspell')return easyUsageQuery(app,week);const e=Error('Usage export failed');e.status=r.status;throw e;}
 const decoder=new TextDecoder(),events=[];let buffer='';const take=line=>{if(!line.trim())return;const e=JSON.parse(line),p=e.properties;if(p.time<Date.parse(week.startAt)||p.time>=Date.parse(week.endAt))return;events.push({event:e.event,properties:Object.fromEntries(['platform','app_version','build_number','time','distinct_id','$insert_id','session_id','note_status','source','has_lecture_notes','screen_name','activity_type','activity_schema_version','mp_country_code'].map(k=>[k,p[k]]))});if(events.length>2000000)throw Error('Usage export bounded limit reached');};
 for await(const chunk of r.body){buffer+=decoder.decode(chunk,{stream:true});let i;while((i=buffer.indexOf('\n'))>=0){take(buffer.slice(0,i));buffer=buffer.slice(i+1);}}take(buffer);return usageRows(events,app,week);
}

// Query permission can exist without raw-export permission. Only aggregate set
// counts leave this existing service; EasySpell iOS is never queried here.
export async function easyUsageQuery(app,week){
 const user=process.env.MIXPANEL_EASYSPELL_SERVICE_ACCOUNT_USERNAME||process.env.MIXPANEL_SERVICE_ACCOUNT_USERNAME,secret=process.env.MIXPANEL_EASYSPELL_SERVICE_ACCOUNT_SECRET||process.env.MIXPANEL_SERVICE_ACCOUNT_SECRET;
 if(app.key!=='easyspell'||!user||!secret)throw Error('Android aggregate query unavailable');
 const script=`function main(){return Events({from_date:${JSON.stringify(week.start)},to_date:${JSON.stringify(week.end)},event_selectors:[{event:'session_started'},{event:'activity_completed'}]}).filter(function(e){return e.properties.platform==='android'&&${JSON.stringify(app.mixpanel.versions||[app.mixpanel.minVersion])}.indexOf(e.properties.app_version)>=0&&Number(e.properties.build_number)>=${Number(app.mixpanel.minBuild.android)};}).groupByUser([],function(state,events){state=state||{active:false,core:false};events.forEach(function(e){if(e.name==='session_started')state.active=true;if(e.name==='activity_completed'&&e.properties.activity_schema_version==='activity_v1')state.core=true;});return state;}).groupBy([function(x){return x.value.active?(x.value.core?'core':'no_core'):'not_active';}],mixpanel.reducer.count());}`;
 const response=await fetch((process.env.MIXPANEL_QUERY_BASE_URL||'https://mixpanel.com')+'/api/query/jql?project_id='+app.mixpanel.projectId,{method:'POST',headers:{Authorization:'Basic '+Buffer.from(user+':'+secret).toString('base64'),'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({script}),signal:AbortSignal.timeout(30000)});
 if(!response.ok){await response.body?.cancel();const e=Error('Aggregate identity intersection unavailable');e.status=response.status;throw e;}
 const data=await response.json();if(!Array.isArray(data)||data.some(r=>!['core','no_core','not_active'].includes(r.key?.[0])||!Number.isInteger(r.value)||r.value<0)||new Set(data.map(r=>r.key[0])).size!==data.length)throw Error('Unexpected aggregate partition');
 const core=data.find(r=>r.key[0]==='core')?.value||0,noCore=data.find(r=>r.key[0]==='no_core')?.value||0,active=core+noCore;
 const base={pillar:'Retention & Engagement',source:'Mixpanel Query API / server-side active/core identity intersection',sourceAccount:app.mixpanel.projectId,sourceTimezone:app.mixpanel.timezone||'unverified',definition:'easyspell_android_active_intersection_v1',population:JSON.stringify({versions:app.mixpanel.versions,minBuild:app.mixpanel.minBuild.android}),status:'EARLY',complete:true,unit:'unique identity clusters',denominator:active,notes:'Android only; clean allowlisted builds. Server-side identity grouping intersects session_started with activity_completed/activity_v1, then partitions active identities into core and no-core. Only aggregate counts returned; not independent-count subtraction. Project calendar/tester coverage remains EARLY; no iOS identities or Mixpanel enabled.'};
 return [['Weekly Active Users',active],['Any Core Value Users',core],['Core Value Reach',active?core/active:null],['No Core Value Users',noCore],['No Core Value Reach',active?noCore/active:null]].map(([name,value])=>metric(week,app,name,'Android',{...base,value,...(name.endsWith('Reach')?{unit:'ratio',numerator:name==='Core Value Reach'?core:noCore}:{})}));
}
